create table if not exists public.purchase_activity (
  id bigint generated by default as identity primary key,
  plan text not null check (plan in ('starter', 'creator', 'lifetime')),
  created_at timestamptz not null default now()
);

create index if not exists purchase_activity_created_at_idx
  on public.purchase_activity (created_at desc);

alter table public.purchase_activity enable row level security;
revoke all privileges on table public.purchase_activity from anon, authenticated;
