create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  plan text not null default 'free',
  is_admin boolean not null default false,
  credits_remaining integer not null default 0 check (credits_remaining >= 0),
  credits_reset_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.generations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  source_path text not null,
  reference_path text,
  prompt text not null,
  result_path text,
  status text not null default 'queued' check (status in ('queued', 'processing', 'completed', 'failed')),
  error_message text,
  created_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  stripe_price_id text,
  plan text not null default 'free',
  status text not null default 'inactive',
  current_period_end timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.generations enable row level security;
alter table public.subscriptions enable row level security;

create table if not exists public.stripe_events (
  event_id text primary key,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

create table if not exists public.purchase_activity (
  id bigint generated by default as identity primary key,
  plan text not null check (plan in ('starter', 'creator', 'lifetime')),
  created_at timestamptz not null default now()
);

create index if not exists purchase_activity_created_at_idx
  on public.purchase_activity (created_at desc);

alter table public.stripe_events enable row level security;
alter table public.purchase_activity enable row level security;
revoke all privileges on table public.purchase_activity from anon, authenticated;

create table if not exists public.referral_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  code text not null unique check (code ~ '^[A-Z0-9]{8,20}$'),
  email_sent_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.referral_attributions (
  referred_user_id uuid primary key references auth.users(id) on delete cascade,
  referrer_user_id uuid not null references auth.users(id) on delete cascade,
  referral_code text not null,
  stripe_subscription_id text unique,
  plan text not null check (plan in ('starter', 'creator', 'lifetime')),
  created_at timestamptz not null default now(),
  check (referred_user_id <> referrer_user_id)
);

create table if not exists public.referral_commissions (
  id uuid primary key default gen_random_uuid(),
  referrer_user_id uuid not null references auth.users(id) on delete cascade,
  referred_user_id uuid not null references auth.users(id) on delete cascade,
  stripe_payment_id text not null unique,
  plan text not null check (plan in ('starter', 'creator', 'lifetime')),
  payment_kind text not null check (payment_kind in ('subscription', 'lifetime')),
  gross_amount_cents integer not null check (gross_amount_cents >= 0),
  commission_cents integer not null check (commission_cents >= 0),
  commission_percent integer not null default 20 check (commission_percent in (20, 50)),
  status text not null default 'pending' check (status in ('pending', 'approved', 'paid', 'cancelled')),
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

alter table public.referral_commissions
  drop constraint if exists referral_commissions_commission_percent_check;
alter table public.referral_commissions
  add constraint referral_commissions_commission_percent_check
  check (commission_percent in (20, 50));

create index if not exists referral_attributions_referrer_idx
  on public.referral_attributions (referrer_user_id, created_at desc);
create index if not exists referral_commissions_referrer_idx
  on public.referral_commissions (referrer_user_id, created_at desc);

alter table public.referral_accounts enable row level security;
alter table public.referral_attributions enable row level security;
alter table public.referral_commissions enable row level security;

drop policy if exists "Users read own referral account" on public.referral_accounts;
create policy "Users read own referral account" on public.referral_accounts
  for select using (auth.uid() = user_id);

drop policy if exists "Users read own referral commissions" on public.referral_commissions;
create policy "Users read own referral commissions" on public.referral_commissions
  for select using (auth.uid() = referrer_user_id);

create policy "Users read own profile" on public.profiles
  for select using (auth.uid() = id);
drop policy if exists "Users update own profile" on public.profiles;

create policy "Users read own generations" on public.generations
  for select using (auth.uid() = user_id);
create policy "Users create own generations" on public.generations
  for insert with check (auth.uid() = user_id);

create policy "Users read own subscription" on public.subscriptions
  for select using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
